"""
LayoutSorter - Sorts page blocks by physical book order.

Refactored from: polish_archive.py (Lines 8-26, 34-62)
Original issues fixed:
  - Hardcoded sort weights (L10-17) → config-driven
  - Dead code: header_part variable (L37) → removed
  - No separation between splitting and sorting logic → clean API
"""

import re
import logging

logger = logging.getLogger(__name__)


class LayoutSorter:
    """Splits consolidated text into page blocks and sorts them by
    physical book page sequence using configurable weights."""

    def __init__(self, config: dict):
        weights = dict(config["layout_weights"])
        self.fallback = weights.pop("_fallback", 500)
        self.weights = weights
        self.page_header_marker = config.get("page_header_marker", "## 📖 頁碼：")

    def sort_key(self, page_header: str) -> int:
        """
        Determine the sort position for a given page header string.

        Checks config-defined keywords first, then tries to extract
        a numeric page number. Falls back to the configured default.

        Args:
            page_header: The text following '## 📖 頁碼：' (e.g., '封面', '53', '60~63')

        Returns:
            Integer sort key.
        """
        # Check keyword-based weights from config
        for keyword, weight in self.weights.items():
            if keyword in page_header:
                return weight

        # Try extracting numeric page number
        nums = re.findall(r"\d+", page_header)
        if nums:
            return int(nums[0])

        # Unknown page type
        logger.warning(f"Unknown page header '{page_header}', using fallback weight {self.fallback}")
        return self.fallback

    def split_and_sort(self, content: str) -> list[tuple[str, str]]:
        """
        Split consolidated markdown into page blocks and sort them
        by physical book order.

        Args:
            content: Full text content of the consolidated archive.

        Returns:
            List of (header_line, body_text) tuples, sorted by page order.
        """
        parts = content.split(self.page_header_marker)

        if len(parts) <= 1:
            logger.warning("No page header markers found in content. Nothing to sort.")
            return []

        # parts[0] is the content before the first header (title block)
        # We skip it since it will be re-generated by main_pipeline
        blocks: list[tuple[str, str]] = []

        for part in parts[1:]:
            first_line_end = part.find("\n")
            if first_line_end == -1:
                first_line_end = len(part)

            header_line = part[:first_line_end].strip()
            body = part[first_line_end:]
            blocks.append((header_line, body))

        # Sort by physical page order
        blocks.sort(key=lambda x: self.sort_key(x[0]))
        logger.info(f"Sorted {len(blocks)} page blocks by physical order.")

        return blocks
