"""
========================================================
Context Retriever — Dialogue History Search & Restore
                                            (V5.0)
========================================================
Searches a local SQLite dialogue history database or 
directly scans the IDE brain to rescue broken contexts.
Outputs results in a Markdown-formatted context block 
suitable for injection into a new LLM conversation.

Usage:
    python context_retriever.py --query "encoding"
    python context_retriever.py --session "tech_design"
    python context_retriever.py --recent 5
    python context_retriever.py --scan-ide
    python context_retriever.py --recover-ide "uuid" --export out.md

Options:
    --query       TEXT    Search dialogue content by keyword.
    --session     TEXT    Filter by session ID.
    --recent      INT     Show the N most recent exchanges.
    --scan-ide            Scan the local IDE brain folder for sessions.
    --recover-ide TEXT    Recover a specific IDE session ID safely.
    --limit       INT     Max results to return (default varies by mode).
    --full                Show full content instead of preview.
    --export      FILE    Export results to a Markdown file.

========================================================
"""

import sqlite3
import os
import sys
import argparse
import textwrap
import json
import glob
from pathlib import Path

from transcript_adapter import get_adapter, TranscriptAdapter

__version__ = "5.0.0"

# --- Encoding Safety for Windows terminals (CP932/CP950) ---
sys.stdout.reconfigure(encoding='utf-8')

# --- Configuration ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "dialogue_history.db")

# Path Decoupling: read from environment variable, fall back to default.
# This allows the system to work across different IDEs and platforms
# without hardcoding a vendor-specific path.
IDE_BRAIN_PATH = os.environ.get(
    "IDE_BRAIN_PATH",
    os.path.expanduser(r"~\.gemini\antigravity-ide\brain")
)

# --- Recovery Prompt (Separated: Header + Instruction) ---
# V5 splits the old monolithic RECOVERY_PROMPT into two parts:
#   1. RECOVERY_HEADER  — pure data envelope (no commands)
#   2. RECOVERY_INSTRUCTION — model-agnostic guidance
# This separation prevents Prompt Injection issues when the
# recovery package is fed to different LLM vendors.

RECOVERY_HEADER = """<CONTEXT_RECOVERY_PACKAGE>
========================================================
  Context Recovery Package (Generated by Retriever V5.0)
========================================================
The following records were extracted from a previous
session's dialogue history.
========================================================"""

RECOVERY_INSTRUCTION = """<RECOVERY_INSTRUCTION>
You are receiving a historical dialogue recovery package.
Please internalize the context above and continue the
conversation naturally from where it left off.
Do NOT repeat the recovered content verbatim.
</RECOVERY_INSTRUCTION>"""

def get_connection():
    """
    Establish a READ-ONLY connection to the dialogue database.
    Uses URI mode with ?mode=ro to prevent accidental writes
    and avoid 'database is locked' conflicts with concurrent writers.
    Returns None and prints an error if the DB file is missing.
    """
    if not os.path.exists(DB_PATH):
        print("[ERROR] Database not found. Run db_initializer.py first.")
        print(f"[PATH] Expected: {DB_PATH}")
        return None
    # Read-only connection to avoid lock conflicts
    return sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)


def _escape_like(keyword: str) -> str:
    """
    [SECURITY FIX] Escape SQL LIKE wildcard characters (% and _).
    Without this, user input like '100%' would become '%100%%',
    causing search logic corruption and potential full-table match.
    """
    return keyword.replace('\\', '\\\\').replace('%', '\\%').replace('_', '\\_')


def search_by_keyword(keyword, limit=20):
    """
    Search dialogue content for a keyword (case-insensitive).
    Returns matching rows as a list of tuples.
    [SECURITY FIX] Uses _escape_like to sanitize LIKE wildcards.
    """
    conn = get_connection()
    if not conn:
        return []

    try:
        with conn:
            cursor = conn.cursor()
            safe_keyword = _escape_like(keyword)
            cursor.execute('''
                SELECT session_id, seq_number, timestamp, engine, speaker, content
                FROM dialogues
                WHERE content LIKE ? ESCAPE '\\'
                ORDER BY timestamp DESC
                LIMIT ?
            ''', (f'%{safe_keyword}%', limit))
            return cursor.fetchall()
    finally:
        conn.close()


def search_by_session(session_id, limit=50):
    """
    Retrieve all dialogues belonging to a specific session.
    Supports partial matching on session_id.
    [SECURITY FIX] Uses _escape_like to sanitize LIKE wildcards.
    """
    conn = get_connection()
    if not conn:
        return []

    try:
        with conn:
            cursor = conn.cursor()
            safe_session = _escape_like(session_id)
            cursor.execute('''
                SELECT session_id, seq_number, timestamp, engine, speaker, content
                FROM dialogues
                WHERE session_id LIKE ? ESCAPE '\\'
                ORDER BY seq_number ASC
                LIMIT ?
            ''', (f'%{safe_session}%', limit))
            return cursor.fetchall()
    finally:
        conn.close()


def get_recent(count=10):
    """
    Retrieve the N most recent dialogue exchanges.
    """
    conn = get_connection()
    if not conn:
        return []

    try:
        with conn:
            cursor = conn.cursor()
            cursor.execute('''
                SELECT session_id, seq_number, timestamp, engine, speaker, content
                FROM dialogues
                ORDER BY timestamp DESC
                LIMIT ?
            ''', (count,))
            return cursor.fetchall()
    finally:
        conn.close()


def search_memories_fts(keyword, limit=5):
    """
    Search memories using SQLite FTS5 extension.
    Requires a virtual table 'virtual_memories' to exist in the database.
    Used for high-performance semantic-like full-text search.
    """
    conn = get_connection()
    if not conn:
        return []
    try:
        with conn:
            cursor = conn.cursor()
            # FTS5 uses MATCH for full-text search
            cursor.execute('''
                SELECT session_id, summary, tags, importance, source, updated_at
                FROM virtual_memories
                WHERE virtual_memories MATCH ?
                ORDER BY rank
                LIMIT ?
            ''', (keyword, limit))
            return cursor.fetchall()
    except sqlite3.OperationalError as e:
        print(f"[WARNING] FTS5 search failed (table might not exist): {e}")
        return []
    finally:
        conn.close()


def scan_ide_brain(adapter_name: str = "antigravity"):
    """
    Scan the local IDE brain folder for session logs.
    Delegates all format-specific parsing to the adapter layer.
    """
    print(f"[SCAN] Scanning IDE brain folder: {IDE_BRAIN_PATH}")
    if not os.path.exists(IDE_BRAIN_PATH):
        print(f"[ERROR] IDE brain path not found: {IDE_BRAIN_PATH}")
        return

    adapter = get_adapter(adapter_name)
    sessions = adapter.scan_sessions(IDE_BRAIN_PATH)

    print(f"\n{'='*80}")
    print(f"  IDE Memory Scan Complete - Found {len(sessions)} sessions")
    print(f"{'='*80}\n")

    for s in sessions:
        print(f"[{s.timestamp}] ID: {s.session_id}")
        print(f"  => Theme: {s.theme}...\n")

def recover_ide_session(session_id, adapter_name: str = "antigravity"):
    """
    Recover a specific IDE session ID.
    Delegates transcript parsing to the adapter layer,
    then assembles a model-agnostic Recovery Package.
    """
    print(f"[RECOVER] Attempting to recover IDE session: {session_id}")

    adapter = get_adapter(adapter_name)
    contexts = adapter.parse_session(IDE_BRAIN_PATH, session_id)

    if not contexts:
        print(f"[ERROR] No dialogue found for session {session_id}")
        return ""

    lines = []
    lines.append(RECOVERY_HEADER)
    lines.append("")

    for ctx in contexts:
        role_label = "USER" if ctx.role == "user" else "AI ASSISTANT"
        lines.append(f"### {role_label} [{ctx.timestamp}]")
        lines.append(ctx.content)
        lines.append(f"{'-'*60}\n")

    lines.append("<END_OF_RECOVERY_PACKAGE>")
    lines.append("")
    lines.append(RECOVERY_INSTRUCTION)

    output = "\n".join(lines)
    print(f"[OK] Recovery package generated for {session_id} (Length: {len(output)} chars)")
    return output

def format_as_markdown(results, title="Retrieved Context", full_content=False, limit_used=None):
    """
    Format query results into a Markdown context block
    suitable for LLM context injection.
    Supports full content display mode.
    Shows truncation warning when results hit limit.
    """
    if not results:
        print("[INFO] No matching records found.")
        return ""

    lines = []
    lines.append(f"\n{'='*60}")
    lines.append(f"  {title}")
    lines.append(f"  Found {len(results)} record(s)")
    lines.append(f"{'='*60}\n")

    for row in results:
        session_id, seq, timestamp, engine, speaker, content = row

        if full_content:
            display = content
        else:
            display = content[:300] + "..." if len(content) > 300 else content

        lines.append(f"### [{timestamp}] Session: {session_id} | Seq: {seq}")
        lines.append(f"**Speaker**: {speaker} | **Engine**: {engine}")
        lines.append("```")
        lines.append(display)
        lines.append("```")
        lines.append(f"{'-'*60}")

    # Truncation warning
    if limit_used is not None and len(results) >= limit_used:
        lines.append(f"\n⚠️ Results may be truncated (showing {limit_used}). Use --limit N to see more.")

    output = "\n".join(lines)
    print(output)
    return output


def export_to_file(content: str, filepath: str):
    """
    Export formatted results to a Markdown file.
    """
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"\n[OK] Results exported to: {filepath}")
    except Exception as e:
        print(f"[ERROR] Failed to export: {e}")


def main():
    parser = argparse.ArgumentParser(
        description=f"Dialogue History Context Retriever V{__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python context_retriever.py --query "database"
              python context_retriever.py --session "tech_design"
              python context_retriever.py --scan-ide
              python context_retriever.py --recover-ide "uuid" --export out.md
        """)
    )
    parser.add_argument('--query', type=str, default=None, help='Search keyword')
    parser.add_argument('--session', type=str, default=None, help='Filter by session ID')
    parser.add_argument('--recent', type=int, default=None, help='Show N most recent exchanges')
    parser.add_argument('--scan-ide', action='store_true', help='Scan IDE brain folder for sessions')
    parser.add_argument('--recover-ide', type=str, default=None, help='Recover a specific IDE session ID')
    parser.add_argument('--limit', type=int, default=None, help='Max results to return')
    parser.add_argument('--full', action='store_true', help='Show full content instead of preview')
    parser.add_argument('--export', type=str, default=None, metavar='FILE', help='Export results to a Markdown file')

    args = parser.parse_args()
    output = ""

    if args.scan_ide:
        scan_ide_brain()
        return
        
    elif args.recover_ide:
        output = recover_ide_session(args.recover_ide)
        if args.export and output:
            export_to_file(output, args.export)
        elif output:
            print("\n[HINT] Use --export FILE to save this recovery package.")
        return

    if args.query:
        limit = args.limit if args.limit else 20
        print(f'[SEARCH] Keyword: "{args.query}" (limit: {limit})')
        results = search_by_keyword(args.query, limit=limit)
        output = format_as_markdown(
            results, title=f'Keyword Search: "{args.query}"',
            full_content=args.full, limit_used=limit
        )

    elif args.session:
        limit = args.limit if args.limit else 50
        print(f'[SEARCH] Session: "{args.session}" (limit: {limit})')
        results = search_by_session(args.session, limit=limit)
        output = format_as_markdown(
            results, title=f'Session: "{args.session}"',
            full_content=args.full, limit_used=limit
        )

    elif args.recent is not None:
        count = args.recent
        print(f'[SEARCH] Recent {count} exchanges')
        results = get_recent(count)
        output = format_as_markdown(
            results, title=f'Recent {count} Exchanges',
            full_content=args.full
        )

    else:
        # Default: show 10 most recent
        print('[INFO] No search flag specified. Showing 10 most recent.')
        results = get_recent(10)
        output = format_as_markdown(
            results, title='Recent 10 Exchanges',
            full_content=args.full
        )

    # Export to file if requested
    if args.export and output:
        export_to_file(output, args.export)


if __name__ == "__main__":
    main()
